export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_SEARCHED_ITEMS = 'ADD_SEARCHED_ITEMS';
export const REMOVE_ALL_QUANTITY = 'REMOVE_ALL_QUANTITY'